### ISSUE TITLE
"Clue tooltip" not working

### ISSUE THREAD

**Issue by JLBrocx** [geheur/watson-master-clue-tracker#12]
After this weeks update, it seems the clue tooltip no longer displays on the clue scroll item.

Clue tooltip it enabled and item overlay is enabled but it doesnt show if watson needs the clue or not any more.

The ::watson command still works.

![image](https://github.com/geheur/watson-master-clue-tracker/assets/11243032/96c4bf8b-5616-4363-8bd2-b746207f9696)

**Comment by geheur** [comment]
This is fixed in 1.2.1. go to plugin hub and update the plugin.
Thanks for reporting this.
