### ISSUE TITLE
Doesn't recognise when Watson gives you a master clue

### ISSUE THREAD

**Issue by asherbasher** [geheur/watson-master-clue-tracker#2]
**Describe the bug**
I had an elite clue at Watson, went there and checked him and the plugin correctly updated saying I needed to give him an easy, medium and hard. Gave him those 3 remaining clues and he handed me a master clue. Plugin still says "Watson is ready to give you a master clue."

**To Reproduce**
1. Go to Watson
2. Hand him the clues required to receive a master clue
3. Type ::watson

**Expected behavior**
It would be preferable if the plugin would know that Watson has given a master clue so we don't have to remember to "check" him again after receiving one.

**Comment by geheur** [comment]
I think this happens when your name is a different length from the one on the character I tested this with, and it affects text line wrapping and prevents detection. Should be an easy fix.

**Comment by geheur** [comment]
I'm guessing you have a fairly short username, right? Mine's 11 characters long.

Anyways, there's a fix for this (assuming my guess on what caused it is right) in v1.0.3. re-open this issue if you still find that this is happening.

**Comment by asherbasher** [comment]
> I'm guessing you have a fairly short username, right? Mine's 11 characters long.

Yes, 5 characters.

> Anyways, there's a fix for this (assuming my guess on what caused it is right - can't reasonably test this unfortunately) in v1.0.3. re-open this issue if you still find that this is happening.

Thanks. I've updated and will test as soon as I get another elite clue to hand in. :)

P.S. Your bank tag layouts plugin has to be the best plugin on the hub!

**Comment by geheur** [comment]
Someone in runelite discord tested it and it seems fixed. ty. @thebinaryeagle
