### ISSUE TITLE
Plugin sometimes fails to update when I get the master clue

### ISSUE THREAD

**Issue by vitorebom** [geheur/watson-master-clue-tracker#5]
![image](https://user-images.githubusercontent.com/55747379/153328946-bf97e0fa-b585-4785-acea-7d07bcf9758c.png)
Plugin believes I have 4 clues with Watson even though I just got a master clue from Watson.
Upon checking the stored units the plugin updated normally 
![image](https://user-images.githubusercontent.com/55747379/153329125-4a35a193-eb1f-4fdc-9b45-794eb1d3d1ce.png)
And I got this after handing the 4 clues in my inv to Watson

**Comment by AustinGarrettR** [comment]
Same experience. If you give him a clue, and just hold spacebar till he finishes the dialogue and gives you one, it doesn't update.

**Comment by geheur** [comment]
ugh, tracking this has been such a pain in the ass. Hopefully I get to this before leagues is over and clues are hard to get again.

**Comment by geheur** [comment]
Jagex changed some widget ids. Also, it doesn't work with master scroll boxes. Bit late but hopefully that's the issue. https://github.com/runelite/plugin-hub/pull/2452

**Comment by geheur** [comment]
Outdated, the plugin no longer uses chat dialogue.
