### ISSUE TITLE
BUG: Giving clues to watson adds to the step count

### ISSUE THREAD

**Issue by vitorebom** [geheur/watson-master-clue-tracker#8]
Just handed watson a clue while having one in my invent, the one in the invent progressed by one step when giving the other clue

**Comment by geheur** [comment]
That sounds like an issue with jagex and their game. I don't see how this has anything to do with my plugin. If it could complete steps that would be pretty cool though.

**Comment by vitorebom** [comment]
I don't know if there's a way to add an exception to not increment the counter when interacting with Watson, since he doesnt have any clue steps to talk to him, but as a plan B would making it so clue completions inside his house wouldnt add to the counter fix that? I know theres a master step to the east of his house.

**Comment by vitorebom** [comment]
I'll report this to the clue step plugin, I was assuming it was something to do with Watson cause it only happened at Watson, sorry for the disturbance

**Comment by geheur** [comment]
lol np. reopen this if it turns out to have something to do with my plugin.
